"""Build and install a self-contained WinUx plug-in for Abaqus/CAE."""

from __future__ import print_function

import argparse
import os
from pathlib import Path
import shutil


PLUGIN_DIR = Path(__file__).resolve().parent
PROJECT_DIR = PLUGIN_DIR.parents[1]
CHECKOUT_WINUX_SOURCE = PROJECT_DIR / "WinUx"
BUNDLED_WINUX_SOURCE = PLUGIN_DIR / "WinUx"

_IGNORED_DIRECTORIES = {
    "__pycache__",
    ".git",
    ".pytest_cache",
    ".mypy_cache",
}
_IGNORED_SUFFIXES = {".pyc", ".pyo"}
_LEGACY_LAYOUT_DIRECTORIES = {"app", "WixUx"}


def _ignore(_directory, names):
    return {
        name
        for name in names
        if name in _IGNORED_DIRECTORIES
        or Path(name).suffix.casefold() in _IGNORED_SUFFIXES
    }


def _ignore_plugin_root(directory, names):
    ignored = _ignore(directory, names)
    if Path(directory).resolve() == PLUGIN_DIR:
        ignored.update(
            name for name in names if name in _LEGACY_LAYOUT_DIRECTORIES
        )
    return ignored


def _resolve_winux_source():
    """Support both the repository installer and a deployed plug-in bundle."""
    for source in (CHECKOUT_WINUX_SOURCE, BUNDLED_WINUX_SOURCE):
        if (source / "__main__.py").is_file():
            return source.resolve()
    raise RuntimeError(
        "WinUx source was not found at '{}' or '{}'.".format(
            CHECKOUT_WINUX_SOURCE,
            BUNDLED_WINUX_SOURCE,
        )
    )


def _validate_layout():
    if not (PLUGIN_DIR / "WinUx_plugin.py").is_file():
        raise RuntimeError("WinUx registration file is missing.")
    return _resolve_winux_source()


def _validate_target(target):
    target = Path(target).expanduser().resolve()
    if target.name.casefold() != "winux":
        raise RuntimeError(
            "Install target must end with an explicit WinUx directory: {}".format(
                target
            )
        )
    if target.parent == target or target.parent.parent == target.parent:
        raise RuntimeError("Refusing broad install target: {}".format(target))
    return target


def _remove_generated_cache(root):
    root = Path(root).resolve()
    for directory, child_dirs, files in os.walk(str(root), topdown=False):
        directory_path = Path(directory).resolve()
        if root not in directory_path.parents and directory_path != root:
            raise RuntimeError("Cache cleanup escaped install root: {}".format(
                directory_path
            ))
        for name in files:
            path = directory_path / name
            if path.suffix.casefold() in _IGNORED_SUFFIXES:
                path.unlink()
        for name in child_dirs:
            path = directory_path / name
            if name in _IGNORED_DIRECTORIES and path.is_dir():
                shutil.rmtree(str(path))


def install(target=None):
    """Install launcher files plus a clean copy of canonical WinUx source."""
    winux_source = _validate_layout()
    target = _validate_target(
        target or (Path.home() / "abaqus_plugins" / "WinUx")
    )
    target.parent.mkdir(parents=True, exist_ok=True)

    installing_in_place = target == PLUGIN_DIR.resolve()
    if not installing_in_place:
        shutil.copytree(
            str(PLUGIN_DIR),
            str(target),
            dirs_exist_ok=True,
            ignore=_ignore_plugin_root,
        )

    bundled_package = (target / "WinUx").resolve()
    if target not in bundled_package.parents:
        raise RuntimeError("Unexpected bundled package path: {}".format(
            bundled_package
        ))

    if not installing_in_place:
        # Remove only the two layouts previously generated by this installer.
        for legacy_name in _LEGACY_LAYOUT_DIRECTORIES:
            legacy = (target / legacy_name).resolve()
            if target not in legacy.parents:
                raise RuntimeError("Unexpected legacy path: {}".format(legacy))
            if legacy.is_dir():
                shutil.rmtree(str(legacy))
        if bundled_package.exists():
            shutil.rmtree(str(bundled_package))
        shutil.copytree(
            str(winux_source),
            str(bundled_package),
            ignore=_ignore,
        )
    obsolete_runtime_config = target / "wixux_runtime.json"
    if obsolete_runtime_config.is_file():
        obsolete_runtime_config.unlink()
    _remove_generated_cache(target)

    print("WinUx installed: {}".format(target))
    print("Bundled WinUx: {}".format(bundled_package))
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Install WinUx into the Abaqus user plug-in directory."
    )
    parser.add_argument(
        "--target",
        help="Target WinUx directory (default: ~/abaqus_plugins/WinUx)",
    )
    args = parser.parse_args(argv)
    install(args.target)


if __name__ == "__main__":
    main()
